#!/usr/bin/env python3
"""
Email Duplicate & Near-Duplicate Detection System
==================================================
Analyzes email datasets to identify duplicate/near-duplicate emails,
common phishing patterns, sender campaigns, and generates comprehensive
research-grade reports.

Author: Generated by Kiro AI
Date: 2024
License: MIT

Methodology:
- Text normalization (whitespace, line endings, quoted replies, HTML)
- TF-IDF vectorization with cosine similarity for near-duplicate detection
- Configurable similarity threshold (default: 90%)
- Campaign detection via sender email pattern clustering
- Phishing archetype classification

Usage:
    python email_duplicate_analyzer.py training_set.csv [--threshold 0.90] [--output report.txt]
"""

import csv
import re
import sys
import os
import hashlib
import argparse
import time
from collections import Counter, defaultdict
from difflib import SequenceMatcher
from typing import List, Dict, Tuple, Optional, Set
import math



# =============================================================================
# TEXT NORMALIZATION & PREPROCESSING
# =============================================================================

class TextNormalizer:
    """Normalizes email text to enable meaningful similarity comparison.
    
    Removes formatting artifacts that do not constitute meaningful content
    differences, including:
    - HTML tags and entities
    - Quoted reply markers (>, >>, etc.)
    - Email headers embedded in body
    - Excessive whitespace and line endings
    - MIME encoding artifacts (=20, =3D, etc.)
    - Signatures and disclaimers
    - Unsubscribe/footer boilerplate
    """
    
    # Patterns for quoted-printable encoding
    QP_PATTERN = re.compile(r'=([0-9A-Fa-f]{2})')
    QP_SOFT_LINEBREAK = re.compile(r'=\s*\n')
    
    # HTML removal
    HTML_TAG_PATTERN = re.compile(r'<[^>]+>')
    HTML_ENTITY_PATTERN = re.compile(r'&[a-zA-Z]+;|&#\d+;')

    
    # Quote markers in replies
    QUOTE_MARKER_PATTERN = re.compile(r'^[>\s]*>', re.MULTILINE)
    
    # Email headers in body
    HEADER_PATTERN = re.compile(
        r'^(From|To|Cc|Bcc|Subject|Date|Sent|Reply-To|'
        r'Content-[Tt]ype|MIME-Version|Message-ID|'
        r'X-[A-Za-z-]+|Return-Path):.*$', re.MULTILINE
    )
    
    # URL pattern
    URL_PATTERN = re.compile(r'https?://[^\s<>"\']+')
    
    # Email address pattern
    EMAIL_PATTERN = re.compile(r'[\w.+-]+@[\w.-]+\.\w+')
    
    # Whitespace normalization
    MULTI_SPACE = re.compile(r'[ \t]+')
    MULTI_NEWLINE = re.compile(r'\n{3,}')
    
    # MIME boundary pattern
    MIME_BOUNDARY = re.compile(r'^--[A-Za-z0-9_=.+-]+\s*$', re.MULTILINE)
    
    # Content-type line pattern
    CONTENT_TYPE_LINE = re.compile(
        r'^Content-type:.*$', re.MULTILINE | re.IGNORECASE
    )

    
    @classmethod
    def normalize(cls, text: str) -> str:
        """Full normalization pipeline for similarity comparison."""
        if not text:
            return ""
        
        # Decode quoted-printable soft line breaks
        text = cls.QP_SOFT_LINEBREAK.sub('', text)
        
        # Decode quoted-printable characters
        def decode_qp(match):
            try:
                return chr(int(match.group(1), 16))
            except (ValueError, OverflowError):
                return match.group(0)
        text = cls.QP_PATTERN.sub(decode_qp, text)
        
        # Remove HTML tags
        text = cls.HTML_TAG_PATTERN.sub(' ', text)
        
        # Decode HTML entities
        text = cls.HTML_ENTITY_PATTERN.sub(' ', text)
        
        # Remove MIME boundaries
        text = cls.MIME_BOUNDARY.sub('', text)
        
        # Remove Content-type lines
        text = cls.CONTENT_TYPE_LINE.sub('', text)
        
        # Remove embedded email headers
        text = cls.HEADER_PATTERN.sub('', text)
        
        # Remove quote markers but keep quoted content
        text = cls.QUOTE_MARKER_PATTERN.sub('', text)
        
        # Normalize whitespace
        text = cls.MULTI_SPACE.sub(' ', text)
        text = cls.MULTI_NEWLINE.sub('\n\n', text)
        
        # Strip lines and remove empty lines
        lines = [line.strip() for line in text.split('\n')]
        lines = [line for line in lines if line]
        text = '\n'.join(lines)
        
        # Lowercase for comparison
        text = text.lower().strip()
        
        return text


    @classmethod
    def extract_subject(cls, raw_text: str) -> str:
        """Extract subject from the first line of email content."""
        if not raw_text:
            return ""
        first_line = raw_text.split('\n')[0].strip()
        # Remove common prefixes
        for prefix in ['Re: ', 'Fwd: ', 'FW: ', 'RE: ']:
            if first_line.startswith(prefix):
                first_line = first_line[len(prefix):]
        return first_line
    
    @classmethod
    def extract_body(cls, raw_text: str) -> str:
        """Extract body (everything after first line)."""
        if not raw_text:
            return ""
        lines = raw_text.split('\n', 1)
        if len(lines) > 1:
            return lines[1]
        return ""
    
    @classmethod
    def extract_sender_emails(cls, raw_text: str) -> List[str]:
        """Extract all email addresses from the text."""
        emails = cls.EMAIL_PATTERN.findall(raw_text)
        # Filter out common non-sender addresses
        filtered = []
        skip_patterns = [
            'unsubscribe', 'privacy', 'noreply', 'no-reply',
            'postmaster', 'mailer-daemon'
        ]
        for email in emails:
            email_lower = email.lower()
            if not any(p in email_lower for p in skip_patterns):
                filtered.append(email_lower)
        return filtered
    
    @classmethod
    def extract_urls(cls, raw_text: str) -> List[str]:
        """Extract all URLs from email text."""
        return cls.URL_PATTERN.findall(raw_text)
    
    @classmethod
    def fingerprint(cls, text: str) -> str:
        """Create a content fingerprint (MD5 hash of normalized text)."""
        normalized = cls.normalize(text)
        return hashlib.md5(normalized.encode('utf-8')).hexdigest()



# =============================================================================
# TF-IDF SIMILARITY ENGINE (No External Dependencies)
# =============================================================================

class TFIDFEngine:
    """Lightweight TF-IDF implementation for near-duplicate detection.
    
    Uses cosine similarity on TF-IDF vectors to measure semantic similarity
    between normalized email texts. No external libraries required.
    """
    
    def __init__(self):
        self.vocabulary = {}  # term -> index
        self.idf = {}  # term -> idf value
        self.doc_count = 0
    
    @staticmethod
    def tokenize(text: str) -> List[str]:
        """Simple whitespace + punctuation tokenizer."""
        # Split on non-alphanumeric, keep tokens >= 2 chars
        tokens = re.findall(r'\b[a-z0-9]{2,}\b', text.lower())
        return tokens
    
    def fit(self, documents: List[str]):
        """Build vocabulary and compute IDF from document corpus."""
        self.doc_count = len(documents)
        doc_freq = Counter()
        
        for doc in documents:
            tokens = set(self.tokenize(doc))
            for token in tokens:
                doc_freq[token] += 1
        
        # Build vocabulary (skip very rare and very common terms)
        idx = 0
        for term, freq in doc_freq.items():
            # Skip terms appearing in >95% of docs or only once
            if freq > 1 and freq < self.doc_count * 0.95:
                self.vocabulary[term] = idx
                self.idf[term] = math.log(self.doc_count / (1 + freq))
                idx += 1
    
    def transform(self, text: str) -> Dict[int, float]:
        """Convert text to sparse TF-IDF vector."""
        tokens = self.tokenize(text)
        tf = Counter(tokens)
        total = len(tokens) if tokens else 1
        
        vector = {}
        for term, count in tf.items():
            if term in self.vocabulary:
                idx = self.vocabulary[term]
                tfidf = (count / total) * self.idf[term]
                vector[idx] = tfidf
        return vector

    
    @staticmethod
    def cosine_similarity(vec_a: Dict[int, float], 
                          vec_b: Dict[int, float]) -> float:
        """Compute cosine similarity between two sparse vectors."""
        # Dot product
        dot = 0.0
        for idx, val in vec_a.items():
            if idx in vec_b:
                dot += val * vec_b[idx]
        
        # Magnitudes
        mag_a = math.sqrt(sum(v * v for v in vec_a.values()))
        mag_b = math.sqrt(sum(v * v for v in vec_b.values()))
        
        if mag_a == 0 or mag_b == 0:
            return 0.0
        
        return dot / (mag_a * mag_b)


# =============================================================================
# PHISHING ARCHETYPE CLASSIFIER
# =============================================================================

class PhishingArchetypeClassifier:
    """Identifies common phishing email archetypes based on content analysis.
    
    Archetypes are defined by combinations of:
    - Urgency language
    - Financial/credential requests
    - URL patterns
    - Social engineering tactics
    - Content themes
    """
    
    ARCHETYPES = {
        'NIGERIAN_PRINCE_SCAM': {
            'description': 'Advance-fee fraud / inheritance scam',
            'patterns': [
                r'inherit', r'million\s+(dollar|usd|pound)',
                r'next\s+of\s+kin', r'deceased', r'beneficiary',
                r'transfer.*funds', r'nigeri', r'algeri', r'prince',
                r'diplomat', r'consignment', r'trunk\s+box'
            ],
            'weight': 2
        },

        'PHARMACY_SPAM': {
            'description': 'Fake pharmacy / medication sales',
            'patterns': [
                r'pharmacy', r'viagra', r'cialis', r'pills?',
                r'medication', r'prescription', r'drugstore',
                r'enlargement', r'erectile', r'libido',
                r'generic\s+drugs?', r'canadian\s+(pharmacy|healthcare)',
                r'penis', r'impotence'
            ],
            'weight': 2
        },
        'REPLICA_GOODS': {
            'description': 'Counterfeit merchandise advertising',
            'patterns': [
                r'replica', r'rolex', r'luxury\s+watch',
                r'designer', r'discount.*brand',
                r'fraction.*price', r'high\s+quality.*replica'
            ],
            'weight': 2
        },
        'CREDENTIAL_PHISHING': {
            'description': 'Account/credential theft attempt',
            'patterns': [
                r'verify\s+your\s+(account|identity)',
                r'password.*expir', r'update\s+your\s+(account|info)',
                r'suspended', r'unauthorized\s+(access|activity)',
                r'confirm\s+your\s+(identity|account)',
                r'click\s+here\s+to\s+(verify|confirm|update)',
                r'log\s*in\s+immediately'
            ],
            'weight': 3
        },

        'FINANCIAL_FRAUD': {
            'description': 'Payment/financial fraud attempt',
            'patterns': [
                r'payment\s+(confirm|process|made)',
                r'invoice', r'wire\s+transfer',
                r'bank\s+account', r'credit\s+card\s+number',
                r'financial\s+institution', r'transaction.*amount',
                r'mortgage', r'loan\s+approv'
            ],
            'weight': 2
        },
        'LOTTERY_SCAM': {
            'description': 'Fake lottery/prize notification',
            'patterns': [
                r'congratulations.*won', r'lottery',
                r'prize\s+(claim|winner|notification)',
                r'lucky\s+(winner|number)', r'award\s+notification',
                r'winning\s+(ticket|number|email)'
            ],
            'weight': 2
        },
        'SOFTWARE_PIRACY': {
            'description': 'Pirated software offers',
            'patterns': [
                r'download.*\$\d+', r'adobe', r'dreamweaver',
                r'photoshop', r'microsoft.*\$',
                r'software.*cheap', r'crack', r'serial\s+key',
                r'full\s+version.*free'
            ],
            'weight': 1
        },

        'CREDIT_REPAIR': {
            'description': 'Credit repair/debt services scam',
            'patterns': [
                r'credit\s+(repair|bureau|score|consultation)',
                r'bad\s+credit', r'negative\s+items',
                r'free\s+consultation', r'credit\s+counselor',
                r'remove.*negative'
            ],
            'weight': 2
        },
        'NEWSLETTER_IMPERSONATION': {
            'description': 'Legitimate newsletter impersonation (CNN, BBC, etc.)',
            'patterns': [
                r'daily\s+top\s+10', r'breaking\s+news',
                r'click\s+here.*full\s+story',
                r'custom\s+alert', r'cnn\s+alert'
            ],
            'weight': 1
        },
        'ROMANCE_SCAM': {
            'description': 'Romance/dating lure',
            'patterns': [
                r'dating', r'singles?\s+in\s+your',
                r'meet\s+(hot|sexy|local)', r'lonely',
                r'relationship\s+type.*sex',
                r'dream\s+girl', r'lolita'
            ],
            'weight': 2
        },
        'SOPHISTICATED_PHISHING': {
            'description': 'Professionally written, minimal urgency, resembles legitimate communication',
            'patterns': [
                r'attached\s+(invoice|document|file)',
                r'please\s+(find|see|review)\s+attached',
                r'for\s+your\s+(review|records|reference)',
                r'per\s+our\s+(conversation|discussion)',
                r'follow\s*up'
            ],
            'weight': 3
        }
    }

    
    @classmethod
    def classify(cls, text: str) -> List[Tuple[str, float]]:
        """Classify email into archetype(s) with confidence scores."""
        text_lower = text.lower()
        results = []
        
        for archetype_name, config in cls.ARCHETYPES.items():
            matches = 0
            total_patterns = len(config['patterns'])
            
            for pattern in config['patterns']:
                if re.search(pattern, text_lower):
                    matches += 1
            
            if matches > 0:
                # Confidence = (matches / total_patterns) * weight factor
                confidence = min(1.0, (matches / total_patterns) * 
                               config['weight'])
                if confidence >= 0.15:  # Minimum threshold
                    results.append((archetype_name, confidence))
        
        # Sort by confidence descending
        results.sort(key=lambda x: x[1], reverse=True)
        return results


# =============================================================================
# SENDER CAMPAIGN DETECTION
# =============================================================================

class CampaignDetector:
    """Identifies sender email addresses that belong to the same campaign.
    
    Uses pattern matching to group semantically related addresses such as:
    - nigerianprince03@hotmail.com / algerianprince03@hotmail.com
    - support@bank-secure1.com / support@bank-secure2.com
    """

    
    @staticmethod
    def extract_email_components(email: str) -> Tuple[str, str, str]:
        """Split email into (local_base, numbers, domain)."""
        parts = email.split('@')
        if len(parts) != 2:
            return (email, '', '')
        local, domain = parts
        # Separate numbers from local part
        base = re.sub(r'\d+', '', local)
        numbers = ''.join(re.findall(r'\d+', local))
        return (base, numbers, domain)
    
    @classmethod
    def compute_email_similarity(cls, email_a: str, email_b: str) -> float:
        """Compute similarity between two email addresses."""
        base_a, nums_a, domain_a = cls.extract_email_components(email_a)
        base_b, nums_b, domain_b = cls.extract_email_components(email_b)
        
        # Same domain boost
        domain_sim = 1.0 if domain_a == domain_b else 0.3
        
        # Local part similarity (ignoring numbers)
        if base_a and base_b:
            local_sim = SequenceMatcher(None, base_a, base_b).ratio()
        else:
            local_sim = 0.0
        
        # Combined score
        return (local_sim * 0.6 + domain_sim * 0.4)
    
    @classmethod
    def detect_campaigns(cls, sender_list: List[str], 
                         threshold: float = 0.75) -> List[List[str]]:
        """Group sender emails into campaigns based on similarity."""
        if not sender_list:
            return []
        
        # Deduplicate
        unique_senders = list(set(sender_list))
        n = len(unique_senders)
        
        # Build adjacency (union-find approach)
        parent = list(range(n))
        
        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x
        
        def union(x, y):
            px, py = find(x), find(y)
            if px != py:
                parent[px] = py

        
        # Compare all pairs (for reasonable sender counts)
        # For very large sets, use blocking by domain first
        if n > 5000:
            # Block by domain for scalability
            domain_groups = defaultdict(list)
            for i, sender in enumerate(unique_senders):
                domain = sender.split('@')[-1] if '@' in sender else ''
                domain_groups[domain].append(i)
            
            for domain, indices in domain_groups.items():
                for i in range(len(indices)):
                    for j in range(i + 1, len(indices)):
                        sim = cls.compute_email_similarity(
                            unique_senders[indices[i]], 
                            unique_senders[indices[j]]
                        )
                        if sim >= threshold:
                            union(indices[i], indices[j])
        else:
            for i in range(n):
                for j in range(i + 1, n):
                    sim = cls.compute_email_similarity(
                        unique_senders[i], unique_senders[j]
                    )
                    if sim >= threshold:
                        union(i, j)
        
        # Collect groups
        groups = defaultdict(list)
        for i in range(n):
            groups[find(i)].append(unique_senders[i])
        
        # Return groups with more than 1 member
        campaigns = [g for g in groups.values() if len(g) > 1]
        campaigns.sort(key=len, reverse=True)
        return campaigns



# =============================================================================
# MAIN ANALYZER
# =============================================================================

class EmailDuplicateAnalyzer:
    """Main analysis engine orchestrating all components.
    
    Pipeline:
    1. Load and parse CSV data
    2. Normalize email content
    3. Compute fingerprints for exact duplicates
    4. Build TF-IDF model for near-duplicate detection
    5. Cluster near-duplicates using similarity threshold
    6. Classify phishing archetypes
    7. Detect sender campaigns
    8. Generate comprehensive report
    """
    
    def __init__(self, threshold: float = 0.90):
        self.threshold = threshold
        self.normalizer = TextNormalizer()
        self.tfidf = TFIDFEngine()
        self.classifier = PhishingArchetypeClassifier()
        self.campaign_detector = CampaignDetector()
        
        # Data storage
        self.raw_emails = []        # Original text
        self.labels = []            # BENIGN/PHISHING
        self.subjects = []          # Extracted subjects
        self.normalized = []        # Normalized text
        self.fingerprints = []      # MD5 fingerprints
        self.tfidf_vectors = []     # TF-IDF sparse vectors
        self.all_senders = []       # All extracted senders
        self.all_urls = []          # All extracted URLs
        
        # Results
        self.duplicate_groups = []   # Groups of duplicate indices
        self.archetype_results = []  # Per-email archetype classification
        self.campaigns = []          # Detected sender campaigns

    
    def load_csv(self, filepath: str) -> int:
        """Load and parse the training set CSV.
        
        Handles the 2-column format: "LABEL","email_content"
        Returns number of emails loaded.
        """
        print(f"[INFO] Loading dataset from: {filepath}")
        start = time.time()
        
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.reader(f, quotechar='"', quoting=csv.QUOTE_ALL)
            for row_num, row in enumerate(reader, 1):
                if len(row) >= 2:
                    label = row[0].strip().upper()
                    content = row[1].strip()
                    
                    if label in ('BENIGN', 'PHISHING'):
                        self.labels.append(label)
                        self.raw_emails.append(content)
                    elif row_num == 1:
                        # Might be a header row - check
                        if 'label' in label.lower() or 'type' in label.lower():
                            continue  # Skip header
                        else:
                            self.labels.append(label)
                            self.raw_emails.append(content)
                elif len(row) == 1 and row_num == 1:
                    # Possible header
                    continue
        
        elapsed = time.time() - start
        count = len(self.raw_emails)
        print(f"[INFO] Loaded {count:,} emails in {elapsed:.2f}s")
        print(f"[INFO] Labels: BENIGN={self.labels.count('BENIGN'):,}, "
              f"PHISHING={self.labels.count('PHISHING'):,}")
        return count

    
    def preprocess(self):
        """Normalize all emails and extract metadata."""
        print("[INFO] Preprocessing and normalizing emails...")
        start = time.time()
        
        for i, raw in enumerate(self.raw_emails):
            # Extract subject (first line)
            subject = self.normalizer.extract_subject(raw)
            self.subjects.append(subject)
            
            # Normalize full text
            norm = self.normalizer.normalize(raw)
            self.normalized.append(norm)
            
            # Fingerprint
            fp = hashlib.md5(norm.encode('utf-8')).hexdigest()
            self.fingerprints.append(fp)
            
            # Extract senders and URLs
            senders = self.normalizer.extract_sender_emails(raw)
            self.all_senders.append(senders)
            
            urls = self.normalizer.extract_urls(raw)
            self.all_urls.append(urls)
            
            if (i + 1) % 5000 == 0:
                print(f"  ... processed {i+1:,}/{len(self.raw_emails):,}")
        
        elapsed = time.time() - start
        print(f"[INFO] Preprocessing complete in {elapsed:.2f}s")
    
    def find_exact_duplicates(self) -> Dict[str, List[int]]:
        """Find exact duplicates using fingerprints."""
        print("[INFO] Finding exact duplicates via fingerprinting...")
        
        fp_groups = defaultdict(list)
        for idx, fp in enumerate(self.fingerprints):
            fp_groups[fp].append(idx)
        
        # Only keep groups with duplicates
        exact_dupes = {fp: indices for fp, indices in fp_groups.items() 
                      if len(indices) > 1}
        
        total_exact = sum(len(v) for v in exact_dupes.values())
        print(f"[INFO] Found {len(exact_dupes):,} exact duplicate groups "
              f"({total_exact:,} emails)")
        return exact_dupes

    
    def find_near_duplicates(self) -> List[List[int]]:
        """Find near-duplicates using TF-IDF cosine similarity.
        
        Uses a two-phase approach for scalability:
        1. Group by fingerprint (exact matches) 
        2. For unique fingerprints, compare TF-IDF vectors
        
        For datasets >10k emails, uses blocking by subject similarity
        to reduce O(n^2) comparisons.
        """
        print(f"[INFO] Finding near-duplicates (threshold={self.threshold})...")
        start = time.time()
        
        # Get unique representatives (one per fingerprint group)
        fp_to_representative = {}
        for idx, fp in enumerate(self.fingerprints):
            if fp not in fp_to_representative:
                fp_to_representative[fp] = idx
        
        unique_indices = list(fp_to_representative.values())
        unique_texts = [self.normalized[i] for i in unique_indices]
        
        print(f"[INFO] Building TF-IDF model on {len(unique_texts):,} "
              f"unique documents...")
        
        # Fit TF-IDF
        self.tfidf.fit(unique_texts)
        
        # Transform all unique docs
        vectors = []
        for text in unique_texts:
            vectors.append(self.tfidf.transform(text))
        
        print(f"[INFO] Vocabulary size: {len(self.tfidf.vocabulary):,} terms")
        print(f"[INFO] Computing pairwise similarities...")
        
        # Union-Find for clustering
        n = len(unique_indices)
        parent = list(range(n))
        
        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x
        
        def union(x, y):
            px, py = find(x), find(y)
            if px != py:
                parent[px] = py

        
        # For scalability: use subject-based blocking for large datasets
        comparisons = 0
        if n > 2000:
            # Block by first 3 words of normalized subject
            blocks = defaultdict(list)
            for i, idx in enumerate(unique_indices):
                subj_words = self.normalized[idx][:100].split()[:3]
                block_key = ' '.join(subj_words[:2]) if subj_words else ''
                blocks[block_key].append(i)
            
            # Also create length-based blocks as fallback
            len_blocks = defaultdict(list)
            for i, text in enumerate(unique_texts):
                # Group by text length bucket (within 20% range)
                bucket = len(text) // max(1, len(text) // 5 + 1)
                len_blocks[bucket].append(i)
            
            # Compare within blocks
            for block_indices in blocks.values():
                if len(block_indices) > 500:
                    continue  # Skip overly large blocks
                for i in range(len(block_indices)):
                    for j in range(i + 1, len(block_indices)):
                        idx_i = block_indices[i]
                        idx_j = block_indices[j]
                        sim = TFIDFEngine.cosine_similarity(
                            vectors[idx_i], vectors[idx_j]
                        )
                        comparisons += 1
                        if sim >= self.threshold:
                            union(idx_i, idx_j)
            
            # Also compare within length blocks
            for block_indices in len_blocks.values():
                if len(block_indices) > 300:
                    continue
                for i in range(len(block_indices)):
                    for j in range(i + 1, len(block_indices)):
                        idx_i = block_indices[i]
                        idx_j = block_indices[j]
                        if find(idx_i) == find(idx_j):
                            continue  # Already grouped
                        sim = TFIDFEngine.cosine_similarity(
                            vectors[idx_i], vectors[idx_j]
                        )
                        comparisons += 1
                        if sim >= self.threshold:
                            union(idx_i, idx_j)
        else:
            # Full pairwise comparison for smaller datasets
            for i in range(n):
                for j in range(i + 1, n):
                    sim = TFIDFEngine.cosine_similarity(
                        vectors[i], vectors[j]
                    )
                    comparisons += 1
                    if sim >= self.threshold:
                        union(i, j)
                
                if (i + 1) % 500 == 0:
                    print(f"  ... compared {i+1}/{n} documents")

        
        # Collect clusters (mapping back to original indices)
        clusters = defaultdict(list)
        for i in range(n):
            root = find(i)
            clusters[root].append(unique_indices[i])
        
        # Expand clusters with exact duplicates
        fp_groups = defaultdict(list)
        for idx, fp in enumerate(self.fingerprints):
            fp_groups[fp].append(idx)
        
        expanded_clusters = []
        for cluster_indices in clusters.values():
            full_group = []
            for idx in cluster_indices:
                fp = self.fingerprints[idx]
                full_group.extend(fp_groups[fp])
            # Deduplicate
            full_group = sorted(set(full_group))
            if len(full_group) > 1:
                expanded_clusters.append(full_group)
        
        elapsed = time.time() - start
        print(f"[INFO] Near-duplicate detection complete in {elapsed:.2f}s")
        print(f"[INFO] Performed {comparisons:,} pairwise comparisons")
        print(f"[INFO] Found {len(expanded_clusters):,} duplicate/near-duplicate groups")
        
        self.duplicate_groups = expanded_clusters
        return expanded_clusters
    
    def classify_archetypes(self):
        """Classify all phishing emails into archetypes."""
        print("[INFO] Classifying phishing archetypes...")
        
        for i, raw in enumerate(self.raw_emails):
            if self.labels[i] == 'PHISHING':
                archetypes = self.classifier.classify(raw)
                self.archetype_results.append(archetypes)
            else:
                self.archetype_results.append([])
        
        # Count archetype frequencies
        archetype_counts = Counter()
        for result in self.archetype_results:
            for archetype, confidence in result:
                if confidence >= 0.3:
                    archetype_counts[archetype] += 1
        
        print(f"[INFO] Archetype distribution:")
        for archetype, count in archetype_counts.most_common(10):
            desc = self.classifier.ARCHETYPES[archetype]['description']
            print(f"  {archetype}: {count:,} emails - {desc}")
        
        return archetype_counts

    
    def detect_sender_campaigns(self):
        """Detect sender campaigns from email addresses."""
        print("[INFO] Detecting sender campaigns...")
        
        # Flatten all senders
        all_senders_flat = []
        for senders in self.all_senders:
            all_senders_flat.extend(senders)
        
        # Count sender frequencies
        sender_counts = Counter(all_senders_flat)
        
        # Detect campaigns among frequent senders
        frequent_senders = [s for s, c in sender_counts.items() if c >= 1]
        self.campaigns = self.campaign_detector.detect_campaigns(
            frequent_senders, threshold=0.70
        )
        
        print(f"[INFO] Found {len(self.campaigns)} sender campaigns")
        for i, campaign in enumerate(self.campaigns[:5]):
            print(f"  Campaign {i+1}: {campaign[:5]}"
                  f"{'...' if len(campaign) > 5 else ''}")
        
        return sender_counts
    
    def get_domain_stats(self) -> Counter:
        """Get statistics on sender domains."""
        domain_counts = Counter()
        for senders in self.all_senders:
            for sender in senders:
                if '@' in sender:
                    domain = sender.split('@')[1]
                    domain_counts[domain] += 1
        return domain_counts

    
    def generate_report(self, output_path: str):
        """Generate comprehensive analysis report."""
        print(f"\n[INFO] Generating report: {output_path}")
        
        total_emails = len(self.raw_emails)
        total_benign = self.labels.count('BENIGN')
        total_phishing = self.labels.count('PHISHING')
        
        # Compute duplicate statistics
        emails_in_dup_groups = set()
        for group in self.duplicate_groups:
            for idx in group:
                emails_in_dup_groups.add(idx)
        
        total_duplicated = len(emails_in_dup_groups)
        dup_percentage = (total_duplicated / total_emails * 100) if total_emails > 0 else 0
        
        # Unique emails (not part of any duplicate group)
        unique_count = total_emails - total_duplicated
        
        # Domain stats
        domain_counts = self.get_domain_stats()
        
        # Sender stats
        all_senders_flat = []
        for senders in self.all_senders:
            all_senders_flat.extend(senders)
        sender_counts = Counter(all_senders_flat)
        
        # Build frequency table for duplicate groups
        group_info = []
        for group in self.duplicate_groups:
            representative = group[0]
            subject = self.subjects[representative]
            label = self.labels[representative]
            frequency = len(group)
            senders = set()
            for idx in group:
                for s in self.all_senders[idx]:
                    senders.add(s)
            
            # Get archetype for phishing emails
            archetype = ''
            if label == 'PHISHING' and self.archetype_results[representative]:
                archetype = self.archetype_results[representative][0][0]
            
            group_info.append({
                'frequency': frequency,
                'subject': subject[:100],
                'label': label,
                'senders': list(senders)[:5],
                'archetype': archetype,
                'representative_idx': representative
            })
        
        # Sort by frequency descending
        group_info.sort(key=lambda x: x['frequency'], reverse=True)

        
        # Archetype statistics
        archetype_counts = Counter()
        for result in self.archetype_results:
            for archetype, confidence in result:
                if confidence >= 0.3:
                    archetype_counts[archetype] += 1
        
        # Write report
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("=" * 80 + "\n")
            f.write("EMAIL DUPLICATE & NEAR-DUPLICATE ANALYSIS REPORT\n")
            f.write("=" * 80 + "\n\n")
            
            f.write("METHODOLOGY\n")
            f.write("-" * 40 + "\n")
            f.write(f"Similarity Threshold: {self.threshold * 100:.0f}%\n")
            f.write("Normalization: Whitespace, HTML, quoted-printable, "
                   "reply markers,\n")
            f.write("               MIME headers, Content-type lines removed\n")
            f.write("Similarity Metric: TF-IDF cosine similarity\n")
            f.write("Exact Duplicates: MD5 fingerprint on normalized text\n")
            f.write("Campaign Detection: Email address pattern clustering "
                   "(union-find)\n")
            f.write("Archetype Classification: Pattern-based with "
                   "confidence scoring\n\n")
            
            # Summary statistics
            f.write("=" * 80 + "\n")
            f.write("SUMMARY STATISTICS\n")
            f.write("=" * 80 + "\n\n")
            f.write(f"Total emails in dataset:        {total_emails:,}\n")
            f.write(f"  - BENIGN:                     {total_benign:,} "
                   f"({total_benign/total_emails*100:.1f}%)\n")
            f.write(f"  - PHISHING:                   {total_phishing:,} "
                   f"({total_phishing/total_emails*100:.1f}%)\n\n")
            f.write(f"Duplicate/Near-Duplicate Groups: "
                   f"{len(self.duplicate_groups):,}\n")
            f.write(f"Emails in duplicate groups:     {total_duplicated:,} "
                   f"({dup_percentage:.1f}%)\n")
            f.write(f"Truly unique emails:            {unique_count:,} "
                   f"({100-dup_percentage:.1f}%)\n\n")

            
            # Duplicate breakdown by label
            dup_benign = sum(1 for idx in emails_in_dup_groups 
                          if self.labels[idx] == 'BENIGN')
            dup_phishing = sum(1 for idx in emails_in_dup_groups 
                            if self.labels[idx] == 'PHISHING')
            f.write(f"Duplicates among BENIGN:         {dup_benign:,}\n")
            f.write(f"Duplicates among PHISHING:       {dup_phishing:,}\n\n")
            
            # Most common email bodies (top duplicate groups)
            f.write("=" * 80 + "\n")
            f.write("MOST FREQUENT DUPLICATE EMAIL BODIES (Top 30)\n")
            f.write("=" * 80 + "\n\n")
            f.write(f"{'#':<4} {'Freq':<6} {'Label':<9} "
                   f"{'Subject':<55} {'Archetype'}\n")
            f.write("-" * 120 + "\n")
            
            for i, info in enumerate(group_info[:30], 1):
                subject_display = info['subject'][:52]
                if len(info['subject']) > 52:
                    subject_display += '...'
                f.write(f"{i:<4} {info['frequency']:<6} "
                       f"{info['label']:<9} "
                       f"{subject_display:<55} "
                       f"{info['archetype']}\n")
            
            f.write(f"\n\n")
            
            # Detailed duplicate group listing
            f.write("=" * 80 + "\n")
            f.write("DETAILED DUPLICATE GROUP REPORT\n")
            f.write("=" * 80 + "\n\n")
            
            for i, info in enumerate(group_info[:50], 1):
                f.write(f"--- Group {i} (Frequency: {info['frequency']}) ---\n")
                f.write(f"  Subject:   {info['subject']}\n")
                f.write(f"  Label:     {info['label']}\n")
                f.write(f"  Archetype: {info['archetype'] or 'N/A'}\n")
                f.write(f"  Senders:   {', '.join(info['senders']) or 'N/A'}\n")
                # Show first 200 chars of body
                rep_idx = info['representative_idx']
                body_preview = self.raw_emails[rep_idx][:200].replace('\n', ' ')
                f.write(f"  Preview:   {body_preview}...\n\n")

            
            # Most common sender email addresses
            f.write("=" * 80 + "\n")
            f.write("MOST COMMON SENDER EMAIL ADDRESSES (Top 30)\n")
            f.write("=" * 80 + "\n\n")
            f.write(f"{'#':<4} {'Count':<8} {'Email Address'}\n")
            f.write("-" * 70 + "\n")
            
            for i, (sender, count) in enumerate(
                    sender_counts.most_common(30), 1):
                f.write(f"{i:<4} {count:<8} {sender}\n")
            
            f.write("\n\n")
            
            # Sender campaigns
            f.write("=" * 80 + "\n")
            f.write("DETECTED SENDER CAMPAIGNS (Semantically Related Addresses)\n")
            f.write("=" * 80 + "\n\n")
            
            if self.campaigns:
                for i, campaign in enumerate(self.campaigns[:20], 1):
                    f.write(f"Campaign {i} ({len(campaign)} addresses):\n")
                    for addr in campaign[:10]:
                        count = sender_counts.get(addr, 0)
                        f.write(f"  - {addr} (appears {count}x)\n")
                    if len(campaign) > 10:
                        f.write(f"  ... and {len(campaign)-10} more\n")
                    f.write("\n")
            else:
                f.write("No multi-address campaigns detected.\n\n")
            
            # Most common sender domains
            f.write("=" * 80 + "\n")
            f.write("MOST COMMON SENDER DOMAINS (Top 30)\n")
            f.write("=" * 80 + "\n\n")
            f.write(f"{'#':<4} {'Count':<8} {'Domain'}\n")
            f.write("-" * 50 + "\n")
            
            for i, (domain, count) in enumerate(
                    domain_counts.most_common(30), 1):
                f.write(f"{i:<4} {count:<8} {domain}\n")
            
            f.write("\n\n")

            
            # Phishing archetypes
            f.write("=" * 80 + "\n")
            f.write("PHISHING ARCHETYPE ANALYSIS\n")
            f.write("=" * 80 + "\n\n")
            f.write(f"{'#':<4} {'Count':<8} {'Archetype':<30} "
                   f"{'Description'}\n")
            f.write("-" * 90 + "\n")
            
            for i, (archetype, count) in enumerate(
                    archetype_counts.most_common(), 1):
                desc = self.classifier.ARCHETYPES[archetype]['description']
                f.write(f"{i:<4} {count:<8} {archetype:<30} {desc}\n")
            
            f.write("\n\n")
            
            # Sophisticated phishing analysis
            f.write("=" * 80 + "\n")
            f.write("SOPHISTICATED PHISHING EMAILS\n")
            f.write("(Short, professional, no urgency, resembles "
                   "legitimate communications)\n")
            f.write("=" * 80 + "\n\n")
            
            sophisticated = []
            for i, raw in enumerate(self.raw_emails):
                if self.labels[i] != 'PHISHING':
                    continue
                
                text_lower = raw.lower()
                body_len = len(raw)
                
                # Check for sophistication indicators
                is_short = body_len < 1000
                has_urgency = bool(re.search(
                    r'act\s+now|immediately|within\s+\d+\s+days?|'
                    r'urgent|expire|deadline|limited\s+time',
                    text_lower
                ))
                has_suspicious_url = bool(re.search(
                    r'http[s]?://[^\s]*\.(xyz|tk|ml|ga|cf|pw|top|club|'
                    r'info/[a-z]{20})',
                    text_lower
                ))
                requests_info = bool(re.search(
                    r'password|ssn|social\s+security|credit\s+card\s+number|'
                    r'bank\s+account\s+number|pin\s+number',
                    text_lower
                ))
                
                if is_short and not has_urgency and not requests_info:
                    sophisticated.append(i)

            
            f.write(f"Found {len(sophisticated)} potentially sophisticated "
                   f"phishing emails\n")
            f.write(f"(Short body, no urgency language, no explicit "
                   f"credential requests)\n\n")
            
            for idx in sophisticated[:20]:
                f.write(f"  [{idx}] Subject: {self.subjects[idx][:70]}\n")
                body_preview = self.raw_emails[idx][:150].replace('\n', ' ')
                f.write(f"       Preview: {body_preview}...\n\n")
            
            # Full frequency table (all duplicate groups)
            f.write("=" * 80 + "\n")
            f.write("COMPLETE FREQUENCY TABLE\n")
            f.write("(All duplicate/near-duplicate groups, sorted by "
                   "descending frequency)\n")
            f.write("=" * 80 + "\n\n")
            f.write(f"{'#':<6} {'Freq':<6} {'Label':<9} "
                   f"{'Senders':<35} {'Subject'}\n")
            f.write("-" * 130 + "\n")
            
            for i, info in enumerate(group_info, 1):
                senders_str = ', '.join(info['senders'][:2])
                if len(info['senders']) > 2:
                    senders_str += '...'
                senders_str = senders_str[:32]
                subject_display = info['subject'][:50]
                f.write(f"{i:<6} {info['frequency']:<6} "
                       f"{info['label']:<9} "
                       f"{senders_str:<35} "
                       f"{subject_display}\n")
            
            f.write(f"\n\nTotal duplicate groups: {len(group_info):,}\n")
            f.write(f"Total emails in groups: {total_duplicated:,}\n")
            f.write(f"Database duplication rate: {dup_percentage:.1f}%\n")
            
            # Footer
            f.write("\n\n" + "=" * 80 + "\n")
            f.write("END OF REPORT\n")
            f.write("=" * 80 + "\n")
            f.write(f"\nGenerated by Email Duplicate Analyzer\n")
            f.write(f"Similarity threshold: {self.threshold*100:.0f}%\n")
            f.write(f"Total emails analyzed: {total_emails:,}\n")
            f.write(f"Report methodology: TF-IDF cosine similarity with "
                   f"content normalization\n")
        
        print(f"[INFO] Report written to: {output_path}")
        print(f"[INFO] Report size: "
              f"{os.path.getsize(output_path)/1024:.1f} KB")

    
    def run_full_analysis(self, csv_path: str, output_path: str):
        """Execute the complete analysis pipeline."""
        print("\n" + "=" * 60)
        print("  EMAIL DUPLICATE & NEAR-DUPLICATE ANALYZER")
        print("=" * 60 + "\n")
        
        total_start = time.time()
        
        # Step 1: Load data
        count = self.load_csv(csv_path)
        if count == 0:
            print("[ERROR] No emails loaded. Check file path and format.")
            sys.exit(1)
        
        # Step 2: Preprocess
        self.preprocess()
        
        # Step 3: Find exact duplicates
        exact_dupes = self.find_exact_duplicates()
        
        # Step 4: Find near-duplicates (includes exact)
        self.find_near_duplicates()
        
        # Step 5: Classify archetypes
        self.classify_archetypes()
        
        # Step 6: Detect campaigns
        self.detect_sender_campaigns()
        
        # Step 7: Generate report
        self.generate_report(output_path)
        
        total_elapsed = time.time() - total_start
        
        # Print summary to console
        total_emails = len(self.raw_emails)
        emails_in_groups = set()
        for group in self.duplicate_groups:
            for idx in group:
                emails_in_groups.add(idx)
        dup_pct = len(emails_in_groups) / total_emails * 100
        
        print(f"\n{'=' * 60}")
        print(f"  ANALYSIS COMPLETE")
        print(f"{'=' * 60}")
        print(f"  Total emails:            {total_emails:,}")
        print(f"  Duplicate groups:        {len(self.duplicate_groups):,}")
        print(f"  Duplication rate:        {dup_pct:.1f}%")
        print(f"  Sender campaigns:        {len(self.campaigns)}")
        print(f"  Total analysis time:     {total_elapsed:.2f}s")
        print(f"  Report saved to:         {output_path}")
        print(f"{'=' * 60}\n")



# =============================================================================
# CLI ENTRY POINT
# =============================================================================

def main():
    """Command-line interface for the email duplicate analyzer."""
    parser = argparse.ArgumentParser(
        description='Email Duplicate & Near-Duplicate Detection System',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python email_duplicate_analyzer.py training_set.csv
  python email_duplicate_analyzer.py training_set.csv --threshold 0.85
  python email_duplicate_analyzer.py training_set.csv --output my_report.txt

Methodology:
  This tool identifies duplicate and near-duplicate emails using:
  1. Text normalization (removes formatting, HTML, quotes, headers)
  2. MD5 fingerprinting for exact duplicate detection
  3. TF-IDF cosine similarity for near-duplicate detection
  4. Pattern-based phishing archetype classification
  5. Union-find clustering for sender campaign detection

  Duplicates are classified as emails exceeding the similarity threshold
  (default 90%) after content normalization.
        """
    )
    
    parser.add_argument(
        'input_file',
        help='Path to the training_set.csv file'
    )
    parser.add_argument(
        '--threshold', '-t',
        type=float,
        default=0.90,
        help='Similarity threshold for near-duplicates (default: 0.90)'
    )
    parser.add_argument(
        '--output', '-o',
        type=str,
        default='duplicate_analysis_report.txt',
        help='Output report file path (default: duplicate_analysis_report.txt)'
    )
    
    args = parser.parse_args()
    
    # Validate input
    if not os.path.exists(args.input_file):
        print(f"[ERROR] Input file not found: {args.input_file}")
        sys.exit(1)
    
    if not 0 < args.threshold <= 1.0:
        print(f"[ERROR] Threshold must be between 0 and 1.0")
        sys.exit(1)
    
    # Run analysis
    analyzer = EmailDuplicateAnalyzer(threshold=args.threshold)
    analyzer.run_full_analysis(args.input_file, args.output)


if __name__ == '__main__':
    main()
